In [2]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [3]:
ch_arr2=np.array(["Supervised","unSupervised","sEMi-supervised","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [4]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [5]:
array1=np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [6]:
array1.dtype

dtype('int32')

In [7]:
char_arr.dtype

dtype('<U1')

In [8]:
ch_arr2.dtype

dtype('<U15')

In [9]:
array3=np.array([1,2,3,4,5,6],dtype='S')

In [10]:
array3

array([b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S1')

In [11]:
array4=np.array([1,2,3,4,5,6],dtype='f')

In [12]:
array4

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [14]:
array2conv=array4.astype('f')
array2conv

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [15]:
array5=array2conv.astype('i')
array5

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [16]:
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [17]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

In [18]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [19]:
ars2=np.zeros(3)
ars2

array([0., 0., 0.])

In [20]:
ars3=np.random.random(3)
ars3

array([0.2662622 , 0.32512758, 0.14794076])

In [22]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [23]:
numone=np.ones((2,3),dtype=int)
numone

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
numone=np.ones((2,2),dtype=float)
numone

array([[1., 1.],
       [1., 1.]])

In [26]:
numone=np.ones((2,1),dtype='S')
numone

array([[b'1'],
       [b'1']], dtype='|S1')

In [27]:
numone=np.ones((3,2))
numone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
dimzeros=np.zeros((3,2,1))
dimzeros

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [34]:
np.info('conv')

Help for conv not found.


In [36]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[6,7,8]])

addition=ar1+ar2
print("addition:\n",addition)

addition:
 [[ 6  8 10]
 [10 12 14]]


In [38]:
subtraction=ar1-ar2
print("subtraction:\n",subtraction)

subtraction:
 [[-4 -4 -4]
 [-2 -2 -2]]


In [39]:
subtraction=ar1*ar2
print("multiplication:\n",multiplication)

subtraction:
 [[ 5 12 21]
 [24 35 48]]


In [40]:
subtraction=ar1/ar2
print("division:\n",division)

subtraction:
 [[0.2        0.33333333 0.42857143]
 [0.66666667 0.71428571 0.75      ]]


In [41]:
power=np.power(ar1,ar2)
print("power:\n",power)

power:
 [[      1      64    2187]
 [   4096   78125 1679616]]


In [43]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([5,6,7])
result=array2d+array1d
result

array([[ 6,  8, 10],
       [ 9, 11, 13]])

In [44]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [51]:
a=np.random.randint(low=2,high=3,size=(2,3))
a

array([[2, 2, 2],
       [2, 2, 2]])

In [52]:
np.concatenate([ar1,ar2])

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [54]:
flatarr=array2d.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [55]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [57]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3
