In [1]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [5]:
type(array1)

numpy.ndarray

In [7]:
array2=np.array([[1,2],
                 [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [9]:
array3d=np.array([[
                    [1,2],
                    [3,4]
                  ],
                  [
                    [5,6],
                    [7,8]
                  ]
                 ])
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
array3ex=np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[10,11,12],
                    [13,14,15],
                    [16,17,18]]
                  ])
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
array4d=np.array([
                    [
                        [
                            [1,2],
                            [3,4],
                            [5,6]
                        ],
                        [
                            [7,8],
                            [9,10],
                            [11,12]
                        ],
                        [
                            [13,14],
                            [15,16],
                            [17,18]
                        ],
                        [
                            [19,20],
                            [21,22],
                            [23,24]
                        ],
                        [
                            [25,26],
                            [27,28],
                            [29,30]
                        ],
                        [
                            [31,32],
                            [33,34],
                            [35,36]
                        ]
                    ]
])
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [15]:
array5ex=np.array((12,13,14))
array5ex

array([12, 13, 14])

In [17]:
print(array1.ndim)

1


In [19]:
print(array2.ndim)

2


In [21]:
print(array3d.ndim)

3


In [23]:
print(array3ex.ndim)

3


In [25]:
print(array4d.ndim)

4


In [27]:
print(array5ex.ndim)

1


In [31]:
array6=np.array([1,2,3,4,5], ndmin=2)
array6

array([[1, 2, 3, 4, 5]])

In [33]:
print(array6.ndim)

2


In [35]:
array6.shape

(1, 5)

In [37]:
array1.shape

(3,)

In [39]:
array2.shape

(2, 2)

In [41]:
array3d.shape

(2, 2, 2)

In [43]:
array3ex.shape

(2, 3, 3)

In [45]:
array4d.shape

(1, 6, 3, 2)

In [47]:
array5ex.shape

(3,)

In [49]:
array2

array([[1, 2],
       [3, 4]])

In [51]:
array2[0][1]

np.int64(2)

In [53]:
array7=np.array([[1,2],[3.3,4]])
array7

array([[1. , 2. ],
       [3.3, 4. ]])